WykopClone/Controllers/ThreadsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using WykopClone.Data;
using WykopClone.Models;

namespace WykopClone.Controllers
{
    public class ThreadsController : Controller
    {
        private readonly DataContext _context;

        public ThreadsController(DataContext context)
        {
            _context = context;
        }

        // GET: Threads
        public async Task<IActionResult> Index()
        {
              return View(await _context.Threads.ToListAsync());
        }

        // GET: Threads/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Threads == null)
            {
                return NotFound();
            }

            var thread = await _context.Threads
                .FirstOrDefaultAsync(m => m.Id == id);
            if (thread == null)
            {
                return NotFound();
            }

            return View(thread);
        }

        // GET: Threads/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Threads/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Models.AddThread newthread)
        {
                var thread = new Models.Thread()
                {
                    Description = newthread.Description,
                    Title = newthread.Title,
                    Link = newthread.Link,
                    Category = newthread.Category
                };
                await _context.Threads.AddAsync(thread);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
        }

        // GET: Threads/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Threads == null)
            {
                return NotFound();
            }

            var thread = await _context.Threads.FindAsync(id);
            if (thread == null)
            {
                return NotFound();
            }
            return View(thread);
        }

        // POST: Threads/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Title,Description,Votes,Category")] Models.Thread thread)
        {
            if (id != thread.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(thread);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ThreadExists(thread.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(thread);
        }

        // GET: Threads/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Threads == null)
            {
                return NotFound();
            }

            var thread = await _context.Threads
                .FirstOrDefaultAsync(m => m.Id == id);
            if (thread == null)
            {
                return NotFound();
            }

            return View(thread);
        }

        // POST: Threads/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            if (_context.Threads == null)
            {
                return Problem("Entity set 'DataContext.Threads'  is null.");
            }
            var thread = await _context.Threads.FindAsync(id);
            if (thread != null)
            {
                _context.Threads.Remove(thread);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool ThreadExists(int id)
        {
          return _context.Threads.Any(e => e.Id == id);
        }

        //Categories threads
        public async Task<IActionResult> Other()
        {
            return View(await _context.Threads.Where(x => x.Category == Models.Thread.CategoryType.Inna).ToListAsync());
        }     
        public async Task<IActionResult> Info()
        {
            return View(await _context.Threads.Where(x => x.Category == Models.Thread.CategoryType.Informacje).ToListAsync());
        }
        public async Task<IActionResult> Entertainment()
        {
            return View(await _context.Threads.Where(x => x.Category == Models.Thread.CategoryType.Rozrywka).ToListAsync());
        }
        public async Task<IActionResult> Sport()
        {
            return View(await _context.Threads.Where(x => x.Category == Models.Thread.CategoryType.Sport).ToListAsync());
        }
        public async Task<IActionResult> Politics()
        {
            return View(await _context.Threads.Where(x => x.Category == Models.Thread.CategoryType.Polityka).ToListAsync());
        }
        public async Task<IActionResult> Travels()
        {
            return View(await _context.Threads.Where(x => x.Category == Models.Thread.CategoryType.Podróże).ToListAsync());
        }
        public async Task<IActionResult> Technology()
        {
            return View(await _context.Threads.Where(x => x.Category == Models.Thread.CategoryType.Technologia).ToListAsync());
        }
        public async Task<IActionResult> Economy()
        {
            return View(await _context.Threads.Where(x => x.Category == Models.Thread.CategoryType.Gospodarka).ToListAsync());
        }
        public async Task<IActionResult> Motorization()
        {
            return View(await _context.Threads.Where(x => x.Category == Models.Thread.CategoryType.Motoryzacja).ToListAsync());
        }
        public async Task<IActionResult> Facts()
        {
            return View(await _context.Threads.Where(x=>x.Category== Models.Thread.CategoryType.Ciekawostki).ToListAsync());
        }

    }
}

WykopClone/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WykopClone</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/WykopClone.styles.css" asp-append-version="true" />
</head>
<body style="background-color:#292828
">
    <header>
        
        <nav class="navbar fixed-top navbar-expand-sm navbar-light bg-dark border-bottom box-shadow ">
            <div class="container-fluid">
                <a class="navbar-brand text-light" asp-area="" asp-controller="" asp-action="">WykopClone</a>                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item hover-nav">
                            <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Index">Główna</a>
                        </li>
                        <li class="nav-item hover-nav">
                            <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Index">Wykopalisko</a>
                        </li>
                        <li class="nav-item hover-nav">
                            <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Index">Mikroblog</a>
                        </li>
                    </ul>
                </div>
                <partial name="_LoginPartial" />
            </div>
        </nav>
        <div class="ml-5">
            <div class="navbar-collapse fix-left-panel collapse">
            <ul class=" navbar-nav flex-column flex-grow-2">
                    <li class=" nav-item nav-item-left hover-nav">
                        <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Create"><img src="Images/create.png" width="50" height="50" /></a>
                </li>
                    <li class=" nav-item nav-item-left hover-nav p-1">
                        <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Other">Inne</a>
                </li>
                    <li class="nav-item nav-item-left hover-nav p-1">
                    <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Facts">Ciekawostki</a>
                </li>
                    <li class="nav-item nav-item-left hover-nav p-1">
                        <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Info">Informacje</a>
                </li>
                    <li class="nav-item nav-item-left hover-nav p-1">
                        <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Entertainment">Rozrywka</a>
                </li>
                    <li class="nav-item nav-item-left hover-nav p-1">
                        <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Sport">Sport</a>
                </li>
                    <li class="nav-item nav-item-left hover-nav p-1">
                        <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Motorization">Motoryzacja</a>
                </li>
                    <li class="nav-item nav-item-left hover-nav p-1">
                    <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Technology">Technologia</a>
                </li>
                    <li class="nav-item nav-item-left hover-nav p-1">
                        <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Economy">Gospodarka</a>
                </li>
                    <li class="nav-item nav-item-left hover-nav p-1">
                        <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Travels">Podróże</a>
                </li>
                    <li class="nav-item nav-item-left hover-nav p-1">
                        <a class="nav-link text-light" asp-area="" asp-controller="Threads" asp-action="Politics">Polityka</a>
                </li>
            </ul>
        </div>
        </div>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>